export { dashboardService } from "./services/dashboardService";
export * from "./queries/useDashboardInitialQuery";
export * from "./queries/useDashboardAbsensiQuery";
export * from "./queries/useDashboardAlfaQuery";
export * from "./queries/useDashboardJuzDistributionQuery";
export * from "./queries/useMuhafizDashboardSantriQuery";
export * from "./queries/useMuhafizDashboardProgresQuery";
export * from "./queries/useMuhafizDashboardTodayAbsensiQuery";
export * from "./queries/useMuhafizDashboardMonthlyAbsensiQuery";
export * from "./queries/useMuhafizDashboardSetoranQuery";
